---
- name: List backup directory on Windows server using PSRP
  hosts: server.pascalinesoft.com
  connection: psrp
  tasks:
    - name: List contents of the backup directory
      win_shell: dir C:\OpenSSH\OpenSSH-Win64\OpenSSH-Win64
      register: backup_contents

    - name: Display the backup directory contents
      debug:
        var: backup_contents.stdout_lines
