---
- name: Check Backup Directories and Display Contents
  hosts: backup_servers
  tasks:
    - name: Check if /home/migf_backup exists
      stat:
        path: /home/migf_backup
      register: migf_backup

    - name: Check if /home/migb_backup exists
      stat:
        path: /home/migb_backup
      register: migb_backup

    - name: Check if /home/wiki_backup exists
      stat:
        path: /home/wiki_backup
      register: wiki_backup

    - name: Check if /home/support_backup exists
      stat:
        path: /home/support_backup
      register: support_backup

    - name: Get contents of /home/migf_backup
      command: ls -larth /home/migf_backup
      register: migf_backup_contents
      when: migf_backup.stat.exists

    - name: Get contents of /home/migb_backup
      command: ls -larth /home/migb_backup
      register: migb_backup_contents
      when: migb_backup.stat.exists

    - name: Get contents of /home/wiki_backup
      command: ls -larth /home/wiki_backup
      register: wiki_backup_contents
      when: wiki_backup.stat.exists

    - name: Get contents of /home/support_backup
      command: ls -larth /home/support_backup
      register: support_backup_contents
      when: support_backup.stat.exists

    - name: Display backup status and detailed contents
      debug:
        msg: |
          Backup Status:
          - migf_backup: {{ migf_backup.stat.exists }}
            Details:
            {{ migf_backup_contents.stdout_lines | join("\n            ") if migf_backup.stat.exists else "Directory does not exist" }}
          - migb_backup: {{ migb_backup.stat.exists }}
            Details:
            {{ migb_backup_contents.stdout_lines | join("\n            ") if migb_backup.stat.exists else "Directory does not exist" }}
          - wiki_backup: {{ wiki_backup.stat.exists }}
            Details:
            {{ wiki_backup_contents.stdout_lines | join("\n            ") if wiki_backup.stat.exists else "Directory does not exist" }}
          - support_backup: {{ support_backup.stat.exists }}
            Details:
            {{ support_backup_contents.stdout_lines | join("\n            ") if support_backup.stat.exists else "Directory does not exist" }}
