name: MIGRATION
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
actions:
  - action: Push to https://github.com/nasirzeeshan/migration.git
    type: PUSH
    login: nasirzeeshan
    password: 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
    push_tags: false
    git_auth_mode: HTTP
    target_branch: $BUDDY_EXECUTION_BRANCH
    push_url: https://github.com/nasirzeeshan/migration.git
    comment: $BUDDY_EXECUTION_ID
    tag: tagName
    deployment_excludes:
      - /tmp/
    use_custom_gitignore: true
    without_force: false
steps:
  - uses: actions/checkout@v1
with:
fetch-depth: 
- name: Update AUTHORS
run: |
 git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
-name: Create Pull Request
uses: peter-evans/create-pull-request@v4
commit-message: update authors 
title: Update AUTHORS
body: Credit new contributors by updating AUTHORS
branch: update-authors
